export const styles = {
  form: {
    padding: "0px 24px",
    borderRadius: "8px",
    backgroundColor: "#fff",
    boxShadow: "0 4px 12px rgba(0,0,0,0.1)",
    position: "relative",
  },
  header: {
    fontSize: "20px",
    marginBottom: "20px",
    textAlign: "center",
  },
  fieldGroup: {
    width: "100%",
    marginBottom: "16px",
    position: "relative",
  },
  label: {
    display: "block",
    marginBottom: "6px",
    fontWeight: "500",
    fontSize: "14px",
  },
  input: {
    width: "93%",
    padding: "10px",
    border: "1px solid #ccc",
    borderRadius: "4px",
    fontSize: "14px",
  },

  error: {
    marginTop: "5px",
    color: "red",
    fontSize: "13px",
    textAlign: "center",
  },
  shipping: {
    marginTop: "36px",
    fontSize: "16px",
    fontWeight: "500",
    textAlign: "center",
  },
  summary: {
    margin: "10px 0 10px 10px",
    padding: "15px",
    background: "white",
    borderRadius: "8px",
  },
  summaryLine: {
    display: "flex",
    justifyContent: "space-between",
    marginBottom: "8px",
  },
  backBtnBox: {
    backgroundColor: "white",
    borderRadius: "8px",
    height: "50vh",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    margin: "10px",
  },
  backBtn: {
    display: "block",
    padding: "10px 20px",
    backgroundColor: "#ff6f20",
    color: "#fff",
    border: "none",
    borderRadius: "5px",
    textDecoration: "none",
    fontWeight: "bold",
    width: "fit-content",
  },
};
